server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # CORRECCIÓN 1: ID de ruta único y descriptivo
        - id: project-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/projects/**
          # CORRECCIÓN 2: Se elimina StripPrefix
          filters: []

        # CORRECCIÓN 1: ID de ruta único y descriptivo
        - id: company-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/companies/**
          # CORRECCIÓN 2: Se elimina StripPrefix
          filters: []

        - id: student-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/students/**
          # Esta ya estaba correcta (sin StripPrefix)
          filters: []

        - id: coordinator-service-route
          uri: http://localhost:8086
          predicates:
            - Path=/coordinators/**
          # CORRECCIÓN 2: Se elimina StripPrefix
          filters: []

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sistema

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

keycloak:
  client-id: desktop