server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: company-service
          uri: http://localhost:8084
          predicates:
            - Path=/projects/**
          filters:
            - StripPrefix=1

        - id: student-service
          uri: http://localhost:8085
          predicates:
            - Path=/students/**
          filters: []

        - id: coordinator-service
          uri: http://localhost:8086
          predicates:
            - Path=/coordinators/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sistema

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
