server:
  port: 8085
spring:
  application:
    name: student-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:studentdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    # Cuando corras en local, usar치 'localhost'.
    # En Docker, la variable de entorno 'SPRING_RABBITMQ_HOST' lo sobreescribir치 con 'rabbitmq'.
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          # Cuando corras en local, usar치 'localhost'.
          # En Docker, la variable de entorno 'SPRING_SECURITY_...' lo sobreescribir치 con 'http://keycloak:8080/...'.
          issuer-uri: http://localhost:8080/realms/sistema

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

keycloak:
  client-id: desktop