server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coordinationdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234  # cámbialo según corresponda

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true